server:
  port: 8080

spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true

#logging:
#  level:
#   root: debug

# example values

indexing-settings:
  userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com
  sites:
    - url: http://www.salstek.ru
      name: СалаватСтекло
    - url: https://saratovstroysteklo.com
      name: СаратовСтройСтекло
#    - url: https://skillbox.ru
#      name: Skillbox
#    - url: https://dimonvideo.ru/
#      name: DimonVideo
#    - url: http://radiomv.ru/
#      name: RadioMv
